export const main = {
  GET_TODOS_REQUEST: "MAIN_GET_TODOS_REQUEST",
  GET_TODOS_SUCCESS: "MAIN_GET_TODOS_SUCCESS",
  GET_TODOS_FAILURE: "MAIN_GET_TODOS_FAILURE",
  UPDATE_TODO_REQUEST: "MAIN_UPDATE_TODO_REQUEST",
  UPDATE_TODO_SUCCESS: "MAIN_UPDATE_TODO_SUCCESS",
  UPDATE_TODO_FAILURE: "MAIN_UPDATE_TODO_FAILURE"
};
